# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-16 06:06
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180115_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='anonymous', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='lmglat',
            field=models.CharField(blank=True, help_text='위도/경도 포맷으로 바꿈', max_length=50, validators=[blog.models.lnglat_validator]),
        ),
    ]
