# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-16 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180116_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='satus',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], default='d', max_length=1),
            preserve_default=False,
        ),
    ]
